name: 删除过于陈旧的Release
on:
    workflow_dispatch:
      inputs:
        release_drop:
          description: '是否删除Release'
          required: true
          default: '是'
          type: choice
          options:
            - "是"
            - "否"
        release_keep_count:
          description: '你希望保留多少个Release'
          required: true
          default: '30'
        release_drop_tag:
          description: '是否删除Release的tag标签'
          required: true
          default: '是'
          type: choice
          options:
            - "是"
            - "否"
        pre_release_drop:
          description: '是否删除预发布版本 Pre-release'
          required: true
          default: '是'
          type: choice
          options:
            - "是"
            - "否"
        pre_release_keep_count:
          description: '你希望保留多少个预发布版本 Pre-release'
          required: true
          default: '0'
        pre_release_drop_tag:
          description: '是否删除预发布版本 Pre-release 的tag标签'
          required: true
          default: '是'
          type: choice
          options:
            - "是"
            - "否"
        draft_drop:
          description: '是否删除Release草稿'
          required: true
          default: '是'
          type: choice
          options:
            - "是"
            - "否"
        draft_drop_count:
          description: '你希望保留多少个Release草稿'
          required: true
          default: '0'

jobs:
  Dele_Old_Github_Releae:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: 对用户提交的数据进行处理，使其能够被正确识别
        run: |
          mkdir -p ${{ github.workspace }}
          touch ${{ github.workspace }}/Change_Github_Enviroment.sh
          cat << EOF > ${{ github.workspace }}/Change_Github_Enviroment.sh
          #!/bin/bash

          # 检查 bc 是否安装
          if ! command -v bc &> /dev/null
          then
              echo "bc 未安装，正在尝试安装..."
              # 尝试安装 bc，这里以 Ubuntu 系统为例，其他系统可能需要不同的包管理器
              sudo apt-get update && sudo apt-get install -y bc
              if [ $? -ne 0 ]; then
                  echo "bc 安装失败，请手动安装 bc。"
                  exit 1
              fi
          else
              echo "bc 已安装。"
          fi

          # 显示所有输入参数的原始值
          echo "原始输入参数:"
          echo "release_drop=${{ github.event.inputs.release_drop }}"
          echo "release_keep_count=${{ github.event.inputs.release_keep_count }}"
          echo "release_drop_tag=${{ github.event.inputs.release_drop_tag }}"
          echo "pre_release_drop=${{ github.event.inputs.pre_release_drop }}"
          echo "pre_release_keep_count=${{ github.event.inputs.pre_release_keep_count }}"
          echo "pre_release_drop_tag=${{ github.event.inputs.pre_release_drop_tag }}"
          echo "draft_drop=${{ github.event.inputs.draft_drop }}"
          echo "draft_drop_count=${{ github.event.inputs.draft_drop_count }}"

          # 检查 release_drop 输入，如果是 "是"，则设置为 true，否则设置为 false
          if [[ ${{ github.event.inputs.release_drop }} == "是" ]] ; then
              echo "release_drop=true" >> $GITHUB_ENV
              echo "设置 release_drop 为 true"
          else 
              echo "release_drop=false" >> $GITHUB_ENV
              echo "设置 release_drop 为 false"
          fi

          # 检查 release_keep_count 输入，如果大于等于 0，减 1 并写入环境变量，否则设置为 15
          echo "环境变量 release_keep_count=${{ github.event.inputs.release_keep_count }}"
          if [ ${{ github.event.inputs.release_keep_count }} -ge 0 ]; then
              echo "release_keep_count=$(echo "${{ github.event.inputs.release_keep_count }} - 1" | bc)" >> $GITHUB_ENV
              echo "设置 release_keep_count 为 $(echo "${{ github.event.inputs.release_keep_count }} - 1" | bc)"
          else 
              echo "release_keep_count=15" >> $GITHUB_ENV
              echo "设置 release_keep_count 为 15"
          fi

          # 检查 release_drop_tag 输入，如果是 "是"，则设置为 true，否则设置为 false
          if [[ ${{ github.event.inputs.release_drop_tag }} == "是" ]] ; then
              echo "release_drop_tag=true" >> $GITHUB_ENV
              echo "设置 release_drop_tag 为 true"
          else 
              echo "release_drop_tag=false" >> $GITHUB_ENV
              echo "设置 release_drop_tag 为 false"
          fi

          # 检查 pre_release_drop 输入，如果是 "是"，则设置为 true，否则设置为 false
          if [[ ${{ github.event.inputs.pre_release_drop }} == "是" ]] ; then
              echo "pre_release_drop=true" >> $GITHUB_ENV
              echo "设置 pre_release_drop 为 true"
          else 
              echo "pre_release_drop=false" >> $GITHUB_ENV
              echo "设置 pre_release_drop 为 false"
          fi

          # 检查 pre_release_keep_count 输入，如果大于等于 0，减 1 并写入环境变量，否则设置为 -1
          echo "环境变量 pre_release_keep_count=${{ github.event.inputs.pre_release_keep_count }}"
          if [ ${{ github.event.inputs.pre_release_keep_count }} -ge 0 ]; then
              echo "pre_release_keep_count=$(echo "${{ github.event.inputs.pre_release_keep_count }} - 1" | bc)" >> $GITHUB_ENV
              echo "设置 pre_release_keep_count 为 $(echo "${{ github.event.inputs.pre_release_keep_count }} - 1" | bc)"
          else 
              echo "pre_release_keep_count=-1" >> $GITHUB_ENV
              echo "设置 pre_release_keep_count 为 -1"
          fi

          # 检查 pre_release_drop_tag 输入，如果是 "是"，则设置为 true，否则设置为 false
          if [[ ${{ github.event.inputs.pre_release_drop_tag }} == "是" ]] ; then
              echo "pre_release_drop_tag=true" >> $GITHUB_ENV
              echo "设置 pre_release_drop_tag 为 true"
          else 
              echo "pre_release_drop_tag=false" >> $GITHUB_ENV
              echo "设置 pre_release_drop_tag 为 false"
          fi

          # 检查 draft_drop 输入，如果是 "是"，则设置为 true，否则设置为 false
          if [[ ${{ github.event.inputs.draft_drop }} == "是" ]] ; then
              echo "draft_drop=true" >> $GITHUB_ENV
              echo "设置 draft_drop 为 true"
          else 
              echo "draft_drop=false" >> $GITHUB_ENV
              echo "设置 draft_drop 为 false"
          fi

          # 检查 draft_drop_count 输入，如果大于等于 0，减 1 并写入环境变量，否则设置为 -1
          echo "环境变量 draft_drop_count=${{ github.event.inputs.draft_drop_count }}"
          if [ ${{ github.event.inputs.draft_drop_count }} -ge 0 ]; then
              echo "draft_drop_count=$(echo "${{ github.event.inputs.draft_drop_count }} - 1" | bc)" >> $GITHUB_ENV
              echo "设置 draft_drop_count 为 $(echo "${{ github.event.inputs.draft_drop_count }} - 1" | bc)"
          else 
              echo "draft_drop_count=-1" >> $GITHUB_ENV
              echo "设置 draft_drop_count 为 -1"
          fi
          EOF
          chmod +x ${{ github.workspace }}/Change_Github_Enviroment.sh
          ${{ github.workspace }}/Change_Github_Enviroment.sh

      - uses: sgpublic/delete-release-action@v1.1
        with:
          #操作仓库
          # repo: ${{ github.repository }}
          #是否删除Release
          release-drop: ${{ env.release_drop }}
          #保留Release个数
          release-keep-count: ${{ env.release_keep_count }}
          #是否删除Release的tag标签
          release-drop-tag: ${{ env.release_drop_tag }}
          #是否删除预发布版本 pre-release
          pre-release-drop: ${{ env.pre_release_drop }}
          #保留Pre-Release个数
          pre-release-keep-count: ${{ env.pre_release_keep_count }}
          #是否删除预发布版本 pre-release的tag标签
          pre-release-drop-tag: ${{ env.pre_release_drop_tag }}
          #是否删除Release的草稿
          draft-drop: ${{ env.draft_drop }}
          #保留Release的草稿个数
          draft-drop-count: ${{ env.draft_drop_count }}
        env:
          #认证令牌
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}