name: MegaLinter


on: 
  push:       # 当有代码更新的时候运行
  workflow_dispatch:    #运行手动执行
  pull_request:    #当有拉取请求的时候执行

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      security-events: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        id: ml
        env:
          VALIDATE_ALL_CODEBASE: true         # 对整个代码库都进行验证
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   #认证秘钥
          SARIF_REPORTER: true     #生成 Sarif 报告  (居然有BUG)
          DISABLE_ERRORS: true     #有错误也别报红
          APPLY_FIXES: all  #应用所有 Linter 的修复
          APPLY_FIXES_EVENT: pull_request   #通过 拉取请求的方式 修复
          APPLY_FIXES_MODE: pull_request   #通过创建新分支的方式修复
          PRINT_ALL_FILES: true     #显示具体文件信息
          REPORT_OUTPUT_FOLDER: ${{ github.workspace }}/megalinter-reports  #报告储存路径
          SHOW_ELAPSED_TIME: true #显示已用时间
          
        #上传文件到附件
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MegaLinter reports
          path: |
            ${{ github.workspace }}/megalinter-reports
            mega-linter.log

      # Set APPLY_FIXES_IF var for use in future steps
      - name: Set APPLY_FIXES_IF var
        run: |
          printf 'APPLY_FIXES_IF=%s\n' "${{
            steps.ml.outputs.has_updated_sources == 1 &&
            (
              env.APPLY_FIXES_EVENT == 'all' ||
              env.APPLY_FIXES_EVENT == github.event_name
            ) &&
            (
              github.event_name == 'push' ||
              github.event.pull_request.head.repo.full_name == github.repository
            )
          }}" >> "${GITHUB_ENV}"

      # Set APPLY_FIXES_IF_* vars for use in future steps
      - name: Set APPLY_FIXES_IF_* vars
        run: |
          printf 'APPLY_FIXES_IF_PR=%s\n' "${{
            env.APPLY_FIXES_IF == 'true' &&
            env.APPLY_FIXES_MODE == 'pull_request'
          }}" >> "${GITHUB_ENV}"
          printf 'APPLY_FIXES_IF_COMMIT=%s\n' "${{
            env.APPLY_FIXES_IF == 'true' &&
            env.APPLY_FIXES_MODE == 'commit' &&
            (!contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref))
          }}" >> "${GITHUB_ENV}"

      # Create pull request if applicable
      # (for now works only on PR from same repository, not from forks)
      - name: Create Pull Request with applied fixes
        uses: peter-evans/create-pull-request@v6
        id: cpr
        if: env.APPLY_FIXES_IF_PR == 'true'
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          commit-message: "[MegaLinter] Apply linters automatic fixes"
          title: "[MegaLinter] Apply linters automatic fixes"
          labels: bot

      - name: Create PR output
        if: env.APPLY_FIXES_IF_PR == 'true'
        run: |
          echo "PR Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "PR URL - ${{ steps.cpr.outputs.pull-request-url }}"

      # Push new commit if applicable
      # (for now works only on PR from same repository, not from forks)
      - name: Prepare commit
        if: env.APPLY_FIXES_IF_COMMIT == 'true'
        run: sudo chown -Rc $UID .git/

      - name: Commit and push applied linter fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: env.APPLY_FIXES_IF_COMMIT == 'true'
        with:
          branch: >-
            ${{
              github.event.pull_request.head.ref ||
              github.head_ref ||
              github.ref
            }}
          commit_message: "[MegaLinter] Apply linters fixes"
          commit_user_name: megalinter-bot
          commit_user_email: nicolas.vuillamy@ox.security

    - name: 修正 Sarif 报告文件
      run: |
        cp ${{ github.workspace }}/megalinter-reports/megalinter-report.sarif ${{ github.workspace }}/megalinter-report.sarif
        python fixs-MegaLinter-sarif-json-file.py

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'megalinter-report-sarif.json'
